service: product-catalog-service

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:${aws:accountId}:table/ProductCatalog"
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::prodcut-thumbnails-sakar/*"

functions:
  listProducts:
    handler: bin/main
    events:
      - http:
          path: /products
          method: GET
          cors: true
  createProduct:
    handler: bin/main
    events:
      - http:
          path: /product
          method: POST
          cors: true
  deleteProduct:
    handler: bin/main
    events:
      - http:
          path: /product/{productID}
          method: DELETE
          cors: true
  putItemTriggeredFunction:  # New Lambda function triggered by DynamoDB PutItem event
    handler: bin/putItemTriggeredFunction
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - "aws.dynamodb"
            detail-type:
              - "AWS API Call via CloudTrail"
            detail:
              eventName:
                - "PutItem"
              requestParameters:
                tableName:
                  - "ProductCatalog"
    # Associate the custom inline policy with the putItemTriggeredFunction
    role: PutItemTriggeredFunctionRole

resources:
  Resources:
    ProductCatalogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductCatalog
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    ThumbnailBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: prodcut-thumbnails-sakar
    PutItemTriggeredFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: PutItemTriggeredFunctionPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "arn:aws:logs:*:*:*"
                - Effect: Allow
                  Action:
                    - dynamodb:DescribeStream
                    - dynamodb:GetRecords
                    - dynamodb:GetShardIterator
                    - dynamodb:ListStreams
                  Resource: "arn:aws:dynamodb:us-east-1:${aws:accountId}:table/ProductCatalog"